### ISSUE TITLE
Should this add-on be able to be uninstalled?

### ISSUE THREAD

**Issue by arborrow** [moodleou/moodle-quizaccess_honestycheck#1]
Tim,

I noticed that quizaccess plugins do not seem to be un-installable by default

mod/quiz/classes/plugininfo/quizaccess.php - declares

  public function is_uninstall_allowed() {
        return false;
    }

Is there a good reason not to be able to uninstall a quizaccess addon or would it be helpful to have honestycheck override that function so that it could be uninstalled? Thanks for any feedback you may have.

Peace - Anthony

**Comment by timhunt** [comment]
Right. This is not an issue with this specific plugin. Closing. (Not sure if the core Moodle issue ever got fixed.)
