### ISSUE TITLE
The submissionstatementdefault | mod_assign String is not shown/used in the selected language.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodleou/moodle-quizaccess_honestycheck#3]
Hi Tim.
We use the Acknowledge plagiarism statement access rule plugin in a 2.6 server at my University, which is a mexican-Spanish site.
When I used a student role I noticed that the plagiarism statement always appears in English, even though it is properly translated in AMOS.
When I use the debuggin option to show origin of languages strings plus the &strings=1 in the web address, I can see the strings used for most messages {in curly brackets}, but the text "This assignment is my own work, except where I have acknowledged the use of the works of other people."  has no culy brackets associated, so I fear Moodle 2.6 is using a hard-wired English language string insted of the translatable variable submissionstatementdefault | mod_assign .

I will greatly appreciatte your help on this issue.

I think you have a multi-lingual site. Could you please check it ?(the mexican spanish language pack is 100% translated)

**Comment by timhunt** [comment]
The statement does come from the language file. Component quizaccess_honestycheck string honestycheckstatement.

See https://lang.moodle.org/local/amos/view.php & https://github.com/moodleou/moodle-quizaccess_honestycheck/blob/master/rule.php#L48 for proof.

**Comment by germanvaleroelizondo** [comment]
My fault. I apologize.

I had failed to customize the default message text at assign | submissionstatement inside my server:
"This assignment is my own work, except where I have acknowledged the use of the works of other people."

I had naively thought that the default text should have been updated by the language pack updates. :(

Thanks for your quick answer.
