### ISSUE TITLE
undefined $CFG

### ISSUE THREAD

**Issue by marinaglancy** [moodleou/moodle-quizaccess_honestycheck#4]
please see comment:
https://tracker.moodle.org/browse/MDL-52523?focusedCommentId=388611&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-388611

**Comment by timhunt** [comment]
I must be missing something. MDL-52523 was a core Moodle but that is now fixed, so of course I was aware of it. Closing this.

**Comment by marinaglancy** [comment]
Hi Tim, i linked to the comment, not the issue.  It says that this particular plugin shows the error about undefined $CFG . I looked at the code and I see it too

**Comment by timhunt** [comment]
If you are interested, read the whole of MDL-52523 and look at what the fix was. That should make it clear. There was a regression in core which I fixed. Sadly, the fix just missed 3.0.1.
