### ISSUE TITLE
Make a honestycheckstatement configurable 

### ISSUE THREAD

**Issue by dmitriim** [moodleou/moodle-quizaccess_honestycheck#8]
Would be good if "honestycheckstatement" could be configurable per quiz instance.

**Comment by timhunt** [comment]
Not necessarily. For us, it is important that everyone uses the centrally approved statement.

So, if you wanted to make this configurable per-quiz, you would need to add a capability, so that most people do not have permission to override the default statement.

**Comment by dmitriim** [comment]
@timhunt how about to start with global value? So just admin will be able to customise.

**Comment by timhunt** [comment]
The test is already configurable by the admin: https://docs.moodle.org/en/Language_customisation

**Comment by dmitriim** [comment]
Unfortunately, it doesn't work in our case as we keep all customised strings in git to make sure we can control the history of them. So basically admins can't change strings without deployment.

I have submitted a patch for that feature, could you please have a look?

**Comment by timhunt** [comment]
If you track you strings in git (we do too), then use git to customise this string.

Sorry, I disagree with this feature. Closing.

**Comment by dmitriim** [comment]
@timhunt sorry for being annoying. 

We really don't  want to fork the public plugin to deliver this feature to our clients and potentially others can benefit from that feature as well. It seems like it doesn't change a lot of the functionality and doesn't add a much of the extra code. The patch is also covered with tests that can make support of it easier in the future. 

We can work on it further if you like. Would you agree with the configurable message per quiz + permissions + admin setting?

**Comment by timhunt** [comment]
I don't really understand your position: You say you want to track strings in git to control the history. If that is what you want, then surely an important string like the plagiarism policy should *really* be tracked in this way?

What does mod_assign do? If you are going to develop anything more complex, making it work the same as mod_assign gives the most consistent UI for users. (However, we have to suppor the OU requirment that this cannot be changed on a per-quiz basis.)

**Comment by dmitriim** [comment]
Sorry, I wasn't explicit enough. In our case the client wants to be able to modify the statement text whenever they want without any deployments and all related paper work involved.
